### ISSUE TITLE
HMR runtime not found for public/app.js.

### ISSUE THREAD

**Issue by dgsunesen** [brunch/brunch-with-redux#6]
Hi,

I keep getting this error when I try to run `brunch watch --server`

`HMR runtime not found for public/app.js. HMR only works if use compile your JS into a single file, could it be the case?`

Anything I need to do in order to run this setup?

**Comment by dgsunesen** [comment]
In my console:

<img width="463" alt="screen shot 2016-10-23 at 16 51 31" src="https://cloud.githubusercontent.com/assets/1023815/19627162/03c7361e-9941-11e6-954c-a9d1f98ba940.png">

**Comment by dgsunesen** [comment]
Built/compiled version works fine.. If i build the project and run a `python -m SimpleHTTPServer` in the `public/` folder it works just fine.

**Comment by douxing** [comment]
same issue for me, any solution?

**Comment by rdiazv** [comment]
+1

**Comment by CuriousCoder17** [comment]
+1

**Comment by RowiDont** [comment]
Just thought you guys might want to know a quick fix for this issue (at least it worked for me).

Go into your package.json and fix `hmr-brunch` and `auto-reload-brunch` to be:
```
    "auto-reload-brunch": "2.7.0",
    "hmr-brunch": "0.1.0",
```

If you are using npm just do `npm install`. I've personally switched to yarn, and this will ensure everything works if you make that switch too.

**Comment by laduke** [comment]
It works if you install brunch master. I can't find brunch's instructions for that. 

I changed my generated package.json to say this:
`"brunch": "https://github.com/brunch/brunch/tarball/master",`
did `npm install`
and used `npm start` to start the dev server.

**Comment by tiranuom** [comment]
Hi all,

I could be able to get it working by disabling the hot deployment feature.

in **brunch-config.json**
`hot : false`

seems like brunch hot-deployment is broken, or there's an issue with non-module file loading order.

**Comment by RowiDont** [comment]
Alternatively, I believe if you go to your package.json and change this:
`"brunch": "^2.8.2"` => `"brunch": "2.8.2"`, that will fix the issue. This is a problem as far as I can tell with brunch v2.9.0+

**Comment by alexkreidler** [comment]
Same issue. Tried above solutions, no success.

**Comment by kockok** [comment]
Is the issue being fixed?? Cause nothing appears on the screen. I'm using Brunch 2.9.1. Should I downgrade to older versions?

**Comment by MEGApixel23** [comment]
@RowiDont Your solution works, thanks! But is there any solution for using with the latest Brunch (current 2.9.1)

**Comment by kockok** [comment]
Reverting back to 2.8.2 works, however, I got another warning `17 Dec 10:00:43 - warn: config.hot: perhaps you meant npm, hooks`

**Comment by razor-x** [comment]
I am currently using https://github.com/brunch/brunch/tree/71727b66ed5606c9b285888c4ac20440ce3560b7 to get this to work. Hopefully we get a new release soon with fixed HMR.

**Comment by denar90** [comment]
Guys, can you verify on latest `brunch` master? Using it everything works fine. Thanks.

**Comment by razor-x** [comment]
Looks like it's working for me on master.

**Comment by paulmillr** [comment]
We're going to release a new release in a bit. You can use `master` for now.

**Comment by razor-x** [comment]
@shvaikalesh I'm not sure if this is strictly related to this issue, but I thought things were working on master until I tried to generate and run a production build. In that case I get `Uncaught ReferenceError: module is not defined`. Could brunch be failing to strip out certain module statements? Anyone else seeing this?

I've rolled all the way back to brunch 2.8.2 to have something stable.

**Comment by shvaikalesh** [comment]
@razor-x Thanks for the report, I will investigate this.

**Comment by razor-x** [comment]
@shvaikalesh Hurray for the new release :) 

This is now in 2.10.0 though. Only happens in production. Could be related to using css modules with postcss. The line giving the error for me is `Uncaught ReferenceError: module is not defined` is

```
    module.exports = {
        'main': 'theme__main___3gw0D',
        'title': 'theme__title___3nVPT',
        'image': 'theme__image___21srf',
        'action': 'theme__action___2vE47',
        'content': 'theme__content___2i84s'
    };
```

which I believe is generated by [this line in postcss-brunch](https://github.com/brunch/postcss-brunch/blob/5e390397a8871aac8b60cb08ea91661471c0333d/index.js#L35):

```
const exports = 'module.exports = ' + JSON.stringify(json) + ';';
```

**Comment by shvaikalesh** [comment]
@razor-x Thanks, but release should not been happened this soon. This helps a lot, I believe it is related to https://github.com/brunch/sass-brunch/issues/133.
